server:
  port: 8080

spring:
  application:
    name: controlbg
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DATABASE}?useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

logging:
  level:
    org:
      springframework:
        web: ERROR
        security: ERROR
      com:
        baomidou:
          mybatis-plus: DEBUG
        apache:
          ibatis: DEBUG

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.conserveit.controlbg.entity
  global-config:
    db-config:
      logic-delete-value: '1'
      logic-not-delete-value: '0'
      logic-delete-field: isDel
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl