name: Maven CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

#on:
#  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: controlbg

    env:
      DB_DATABASE: citdb
      DB_USER: root
      DB_PASSWORD: root

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Set up MySQL
        run: |
            sudo /etc/init.d/mysql start
            mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
      - name: Maven clean
        run: mvn clean
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: MySQL Server Stop
        run: sudo service mysql stop

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          project-path: controlbg/pom.xml